### ISSUE TITLE
Expose Simple Metrics View Through Local Http Page

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#187] opened 2021-02-14 14:52 UTC
Currently a user can view metrics from ZIO ZMX through applications like Grafana. While this is great for the end state of a user who is fully invested in ZMX to get high quality dashboards it creates an initial barrier to new users to get this set up.

It would be good to create a local site users could navigate to in their browser to view basic metrics about their application in a "Hello, World!" style. This would allow users who were first experimenting with ZIO ZMX to confirm that their application was being monitored and view basic metrics before diving in to setting up integration with a dashboard service.

**Comment by fokot** [comment] 2021-02-14 18:31
I can take this. Should I generate the page on the backend (scala-xml will soon be deprecated and it adds dependency) or frontend (I can do it with React and without bundler, so without the need for npm, or even with it)? @adamgfraser

**Comment by iravid** [comment] 2021-02-14 18:31
Would also be useful to get those basic metrics in a JSON formatted response.

**Comment by atooni** [comment] 2021-02-15 05:20
It would probably be very easy to add a JSON encoding to the current Prometheus reporter. It already serves the values to Prometheues via http today and the JSON encoding could be used to display the current values as a simple web page.  

If you were envisioning graphs like in a dashboard, for any current reporter you would some kind of history, which we currently don't have in ZMX. Personally I would choose to display the current values only. If we wanted to go for a viualization with history, I would see that in it's own project - perhaps after ZIO web is advanced enough to start with that. 

Last not least, if we would expose the current values somehow via JMX, we could use Jconsole to look at them and that would also give us rudimentary graphs.

**Comment by adamgfraser** [comment] 2021-02-15 05:24
@atooni I think that makes sense.

**Comment by atooni** [comment] 2021-02-15 05:35
There is one other thing, that comes to my mind. When I did the Prometheus implementation, I just created the Prometheus encoding, which the end user would have to serve using a web server of choice. 

The demos include a sample application using uzhttp. I wanted to avoid pulling in all the dependencies of a web server just to use instrumentation.

**Comment by fokot** [comment] 2021-02-22 21:32
@adamgfraser I wanted to generate zio-json encoders for `PMetric` but I couldn't with this error
```
magnolia: child class <local child> of class PMetric is neither final nor a case class
    DeriveJsonEncoder.gen[PMetric]
```

It is coming from often used anonymous classes like `new PMetric(name, help, labels, Details.GaugeImpl(startAt)) {}`

When I tried to generate it for `Details` I got stuck on the `Quatile` with the same error.

What do you suggest?  Can I change `PMetric` to case class? Or create another `PMetricImpl` case class.

And why is this encoding used? Just have (lazy) calculated values like here?
```
final case class Linear(start: Double, width: Double, count: Int) extends Buckets {
  override def boundaries: Chunk[Double] =
    Chunk.fromArray(0.until(count).map(i => start + i * width).toArray) ++ Chunk(Double.MaxValue)
}
```

**Comment by atooni** [comment] 2021-02-23 17:15
@fokot - Sorry for answering late. I am jumping in as the PMetrics came from one of my PRs. 

The reason the classes were implemented that way is that at first we defined a set of traits that are a direct translation from our understanding of the Prometheus specification for providing new clients. We have then provided an implementation for those interfaces. 

Our primary concern was that we somehow have to keep the current state in memory, so that it can be served via http on request. The split here is between the Datamodel (which I believe you are looking at) and the PrometheusRegistry for keeping the state. 

If I understand correctly, the problem is that the resulting classes are not pure case classes. Perhaps we can refactor those classes, and I would think that the individual `observe` methods are the primary problem. We could probably clean up the case classes and use Magnolia to generate JSON. 

On the other hand, its only a handful of classes, so it might be an option to handcraft a json encoding and use the PrometheusEncoder as a guideline. 

I am away from my desk for a couple of days, but if you wanted we could sync up someday after Friday to look at the code together and discuss how we could refactor it.

**Comment by adamgfraser** [comment] 2021-02-25 01:57
@fokot I think you can turn `PMetric` into a `case class`.

**Comment by fokot** [comment] 2021-03-03 15:59
@adamgfraser can we close this ticket now, or is there more work to be done?

We can encode Prometheus metrics to json, we have a method to get them from `PrometheusInstrumentaion` and in examples in `PrometheusInstrumentedApp` we serve them on http server.

**Closed** 2021-03-08 11:08 UTC
